#! /bin/sh

nitrogen --restore
sxhkd &
polybar -r desktops &
kshare -b &
compton &

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap 2;
bspc config top_padding 1
bspc config left_padding 1
bspc config right_padding 1
bspc config bottom_padding 1

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

